version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu1804
install:
  
before_build:
  - nuget restore ZigBeeNet.sln
build:
  publish_nuget: true
  verbosity: minimal
  project: ZigBeeNet.sln

deploy:
- provider: NuGet
  api_key:
    secure: YML4HxoLllvOC7H38JyYjY7lA2VRUVcA6bqI1vIemivjyL+b2RSjvKMsblEU39/r
  skip_symbols: false
  artifact: /.*\.nupkg/

test:
  # only assemblies to test
  assemblies:
    - '**\*.test.dll'
